name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  ENABLE_FTP_DEPLOY: false   

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Questo consente la scrittura sul repository, incluso il push di tag e modifiche

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Usa la versione aggiornata

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Usa Node.js 20
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm run build:production
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        #VITE_PUBLIC_URL: 'coditec'

    # Semantic Release: solo sui push su main, NON nelle pull request
    - name: Run Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Deploy solo su push su main
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4  # Usa la versione aggiornata
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

    # Deploy via FTP per index.html
    - name: Deploy index.html to FTP root
      if: ${{ env.ENABLE_FTP_DEPLOY == 'true' && github.ref == 'refs/heads/main' }}
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/  # Specifica il file da caricare
        server-dir: /www.coditec.it/  # Destinazione del file index.html
        exclude: assets/**  # Escludi la cartella assets

    # Deploy via FTP per la cartella assets
    - name: Deploy assets to FTP
      if: ${{ env.ENABLE_FTP_DEPLOY == 'true' && github.ref == 'refs/heads/main' }}
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/assets/  # Specifica la cartella da caricare
        server-dir: /www.coditec.it/coditec/assets/  # Destinazione della cartella assets