name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm run build

    - name: Create release branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: git checkout -b release-${{ github.run_number }} && git push origin release-${{ github.run_number }}

    - name: Run Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push release branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: git push origin release-${{ github.run_number }}

    - name: Create Pull Request
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Release ${GITHUB_REF}'
        body: 'Automated release'
        base: main
        branch: release-${{ github.run_number }}

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
