name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Questo consente la scrittura sul repository, incluso il push di tag e modifiche

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Usa la versione aggiornata

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Usa Node.js 20
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm run build:production
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        #VITE_PUBLIC_URL: 'coditec'

    # Semantic Release: solo sui push su main, NON nelle pull request
    - name: Run Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



    - name: Checkout the ftp-deploy branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin ftp-deploy
        git checkout ftp-deploy || git checkout -b ftp-deploy

    - name: Copy the dist folder contents to the root
      run: |
        rm -rf *
        cp -r dist/* .
        rm -rf dist

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update FTP deploy"
        git push origin ftp-deploy
      

    # Deploy via FTP
    - name: Deploy to FTP
      if: github.ref == 'refs/heads/main'  # Solo su push su main
      uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Aggiungi questa azionegit 
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/  # Specifica la cartella di build
        server-dir: /www.coditec.it/  # Percorso di destinazione sul server
